/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'selector',
  content: ['./src/**/*.{html,js,jsx,ts,tsx}'],
  safelist: [
    '!bg-singlife-red-800',
    'bg-singlife-red-800',
    'bg-singlife-red-200',
    'bg-singlife-turquoise-800',
    'bg-singlife-turquoise-200',
    'bg-singlife-purple-800',
    'bg-singlife-purple-200',
    'bg-singlife-orange-800',
    'bg-singlife-orange-200',
    'bg-singlife-black-900',
    'bg-singlife-black-800',
    'bg-singlife-black-200',
    'bg-singlife-black-100',
    'bg-singlife-white',
    'text-singlife-red-800',
    'text-singlife-red-200',
    'text-singlife-turquoise-800',
    'text-singlife-turquoise-200',
    'text-singlife-purple-800',
    'text-singlife-purple-200',
    'text-singlife-orange-800',
    'text-singlife-orange-200',
    'text-singlife-black-900',
    'text-singlife-black-800',
    'text-singlife-black-200',
    'text-singlife-black-100',
    'text-singlife-white',
  ],
  theme: {
    fontFamily: {
      sans: ['Graphik', 'sans-serif'],
      serif: ['Merriweather', 'serif'],
    },
    extend: {
      colors: {
        'singlife-red-800': '#FF0008',
        'singlife-red-200': '#FFE9EC',
        'singlife-turquoise-800': '#19D3C5',
        'singlife-turquoise-200': '#B0ECE6',
        'singlife-purple-800': '#883E89',
        'singlife-purple-200': '#CFAAD0',
        'singlife-orange-800': '#FFA168',
        'singlife-orange-200': '#FFD5BE',
        'singlife-black-900': '#000000',
        'singlife-black-800': '#434343',
        'singlife-black-200': '#DBDBDB',
        'singlife-black-100': '#F2F2F2',
        'singlife-white': '#FFFFFF',
      },
    },
  },
  plugins: [],
}
